const config = require("./config");

module.exports = {
  PORT: config.PORT,
  APP_CONNECTION: config.APP_CONNECTION,
  CLIENT_HOST: config.CLIENT_HOST,
  ADMIN_HOST: config.ADMIN_HOST,
  SERVER_HOST: config.SERVER_HOST,
  GENERATE_CONFIRM_REGISTRATION_PASSWORD_RESET_LINK:
    config.GENERATE_CONFIRM_REGISTRATION_PASSWORD_RESET_LINK,
  APP_ORIGINS: config.APP_ORIGINS,
  IO_PLACEHOLDERS: config.IO_PLACEHOLDERS,
  CLIENT_TERMS_URL: config.CLIENT_TERMS_URL,
  NOTIFICATION_PLACEHOLDERS: config.NOTIFICATION_PLACEHOLDERS,
  CLIENT_UPLOAD_DESTINATION: config.CLIENT_UPLOAD_DESTINATION,
  CLIENT_STATIC_URL_ROOT: config.CLIENT_STATIC_URL_ROOT,
  COMMERCIAL_UPLOAD_DESTINATION: config.COMMERCIAL_UPLOAD_DESTINATION,
  COMMERCIAL_STATIC_URL_ROOT: config.COMMERCIAL_STATIC_URL_ROOT,
};
